--- #YAML:1.0
name:                WWW-httpBL
version:             0.01
abstract:            Perl interface to Project Honeypot's Http:BL Service 
license:             ~
author:              
    - Chris Mills <cmills@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
